package com.itkachuk.pa.entities;

import java.util.Date;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable
public class ExpenseRecord {
	
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	private int id;
	
	@DatabaseField
	private Date date;
	
	@DatabaseField
	private long timestamp; // UTC timestamp in milliseconds
	
	@DatabaseField(canBeNull = false, foreign = true) // 'null' value will correspond to "main" account (non-removable)
	private Account account;
	
	@DatabaseField(canBeNull = false, foreign = true)
	private ExpenseCategory category;
	
	@DatabaseField
	private String description; // can play a role of subcategory
	
	@DatabaseField
	private double amount;
	
	@DatabaseField
	private boolean isRegular; // Record added by service - true, added manually - false
	
	public ExpenseRecord() {
		// needed by ormlite
	}

	public ExpenseRecord(Date date, Account account, ExpenseCategory category,
			String description, double amount, boolean isRegular) {
		super();
		this.timestamp = System.currentTimeMillis();
		this.date = date;
		this.account = account;
		this.amount = amount;
		this.category = category;
		this.description = description;		
		this.isRegular = isRegular;
	}

	public void setId(int recordId) {
		this.id = recordId;
	}
	
	public int getId() {
		return id;
	}
	
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(long millis) {
		this.timestamp = millis;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public ExpenseCategory getCategory() {
		return category;
	}

	public void setCategory(ExpenseCategory category) {
		this.category = category;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public boolean isRegular() {
		return isRegular;
	}

	public void setRegular(boolean isRegular) {
		this.isRegular = isRegular;
	}

	@Override
	public String toString() {
		return "IncomeOrExpenseRecord [id=" + id + ", date=" + date
				+ ", timestamp=" + timestamp + ", account=" + account + ", category="
				+ category + ", description=" + description + ", amount="
				+ amount + ", isRegular=" + isRegular + "]";
	}

}
